### ISSUE TITLE
Not installing latest package thru pip

### ISSUE THREAD

**Issue by krantik** [MomsFriendlyRobotCompany/pycreate2#11]
When I do pip install pycreate2 it seems to install older package and not the newer one that has fixes to MIDI tones.

Also, there is a missing comma line 50 in setup.py when installing from cloned copy and the missing README.rst file. Fixing these two issues will help install from the cloned copy.

**Comment by walchko** [comment]
sorry ... I must not have pushed that to pypi ... give me a little bit and I will push it today. :smile:

**Comment by walchko** [comment]
ok, made some updates and just published 0.7.5 to pypi ... it should be there soon.

**Comment by walchko** [comment]
should be all good now :bento:

**Comment by krantik** [comment]
@walchko thank you very much for taking care of this update. I confirm it is working now, updated the package and now midi tones example works great.
