### ISSUE TITLE
songs don't aways play

### ISSUE THREAD

**Issue by walchko** [MomsFriendlyRobotCompany/pycreate2#3]
The create is finicky with songs. Sometimes they work, sometimes they don't. It could be a bug in my 2007 firmware that came with my new 2017 Create 2.

**Comment by CASELIG** [comment]
Your problem could be this:

The Create 2 has an internal pointer that needs to be reset after each song play. You can do that via a bit of code. See here: http://www.robotappstore.com/Knowledge-Base/7-How-to-program-Roomba-to-sing/21.html

Alternatively you can just turn it off and on again. If it always works first time after it's switched on but is then finicky you probably have a pointer error.

**Comment by walchko** [comment]
thanks ... I will take a look 👍

**Comment by walchko** [comment]
fixed finally
