### ISSUE TITLE
'is_open' deprecated in pySerial

### ISSUE THREAD

**Issue by SohamPardeshi** [MomsFriendlyRobotCompany/pycreate2#7]
Currently does not work with newest version of Python and updated modules. All `ser.is_open` should be replaced with `ser.isOpen()` in createSerial.py

**Comment by walchko** [comment]
The [docs](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#classes) say the other way around:

```python
isOpen()
Deprecated since version 3.0: see is_open
```

interesting

**Comment by walchko** [comment]
So it works for me ... I think you are somehow doing something wrong:

```python
Python 2.7.13 (default, Jul 18 2017, 09:17:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> serial.__version__
'3.4'
>>> s=serial.Serial()
>>> s.is_open
False
```

```python
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> serial.__version__
'3.4'
>>> s=serial.Serial()
>>> s.is_open
False
```

**Comment by SohamPardeshi** [comment]
You're right. Sorry, meant to say all `ser.isOpen()` should be replaced with `ser.is_open` in createSerial.py

**Comment by walchko** [comment]
ok, I meant to remove those ... thanks! they are fixed and pushed an update to pypi. :tada:
